image: istcc:latest

stages:
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - /prep.sh
java:
  stage: test
  script:
    - run_tests.sh
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
